spring:
  application:
    name: ForumSSM
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ljh3927322
    url: jdbc:mysql:///forums_db?useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 80

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# --------------------------用户自定义项--------------------------------------
# 本地文件存储地址
FileRepository: E:/forum_project_save_dir

# 跨域访问放行的源
cors:
 origins:
  - http://10.62.192.125:8080